// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyjcffmjzgcfzkwjellp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5amNmZm1qemdjZnprd2plbGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODg5MzEsImV4cCI6MjA2NzQ2NDkzMX0.pSYrooMJ80e-lg9gFP_EZSVfr-WUgLukdkboy-B5zOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});