// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srqjdcwanbdxqfrkiugt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNycWpkY3dhbmJkeHFmcmtpdWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzQ1NzUsImV4cCI6MjA2ODcxMDU3NX0.aA5Bb6xW4pirMHsq85_-WtbfTotP_RinD4Tm73q_2ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});